name: Auto YouTube Shorts

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download Video
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python download.py

      - name: Edit Video
        run: python edit.py

      - name: Upload Downloaded Video
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-video
          path: output/shorts.mp4
      - name: Upload to YouTube
        env:
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        run: python upload.py
